### ISSUE TITLE
Непрокрас в рекламе

### ISSUE THREAD

**Issue by Russia9** [evtn/vk_wide#3]
## Описание
В новостях в рекламе с каруселью
![изображение](https://user-images.githubusercontent.com/33428293/70312035-daae4f00-1823-11ea-8cfe-ae1fbda62a57.png)

## Шаги для воспроизведения
1. Зайти в раздел новости
2. Найти рекламу с каруселью

## Информация о системе
- Firefox 71.0
- 1920x1080

**Comment by evtn** [comment]
Фикс в 0.3.88
