### ISSUE TITLE
Непрокрас при редактировании сообщения

### ISSUE THREAD

**Issue by Russia9** [evtn/vk_wide#4]
## Описание
При редактировании сообщения, после того как было отредактировано, момент ожидания ответа сервера

![изображение](https://user-images.githubusercontent.com/33428293/70312424-b0a95c80-1824-11ea-9196-0670957e4e0e.png)

## Шаги для воспроизведения
1. Зайти в раздел сообщения
2. Найти любое **уже прочитанное** сообщение
3. Отредактировать его

## Информация о системе
- Firefox 71.0
- 1920x1080

**Comment by evtn** [comment]
Фикс 0.3.89 вместе с парой багов в поле редактирования
